### ISSUE TITLE
Comply with License

### ISSUE THREAD

**Issue by MrJPGames** [tehstone/wayfarer-addons#1]
Nomination map as well as Nominations Stats uses substantial code from either WayFarerPlus and or WayFarerToolkit-Userscripts. As per GPLv3 you are required to:
-  License and copyright notice
-  State changes
-  Disclose source
-  Same license

You failed to include the same license, disclose your source, state any changes you made nor did you include a notice of the original copyright and license!

Please note that as you are distributing these scripts individually, you are required to include the license in the offending scripts themselves, to ensure further private distribution is also lawful.

**Comment by MrJPGames** [comment]
WF+ should be public again: https://github.com/MrJPGames/WayFarerPlus
Even without that this this is enough :)

**Comment by tehstone** [comment]
Thank you, I have been chatting with MarioMc about the future of Wayfarer tools in general so I will make sure the licensing and attribution meets his requirements as well.
