### ISSUE TITLE
[Feature-Request] add lightship.dev to Wayfarer Open-In

### ISSUE THREAD

**Issue by Un1matr1x** [tehstone/wayfarer-addons#52]
**Use case**

If you check nominations in a suspicious area, you will see all approved Wayspots, but you cannot see if there are already approved scans of potentially suspicious Wayspots, which could disprove the suspicion of faking.

**Proposed Solution**

add _https://lightship.dev/account/geospatial-browser/lat,lng,zoom,,_ as Lightship to the providers at the Wayfarer Open-In script

**Pro**
additional way to check for potencial fakes

**Con**
LightShip account needed

**Comment by tehstone** [comment]
The Lightship dev platform is not meant to be open to public use same as with the Wayfarer app at this time so this link will not be added to this plugin.
