### ISSUE TITLE
Keyboard review skipped Signifance and Uniqueness

### ISSUE THREAD

**Issue by exemok** [tehstone/wayfarer-addons#8]
If I press 5-5-5
First is selected global mark, then title / description, then Accessibility. 
Significance and Uniqueness are skipped.

Probably it conflicted with Compact View add-on

**Comment by HaramDingo** [comment]
Aware, and true that it is conflicting with the compact view. It has to do with appending child modules and not retaining the same layout as defined in the keyboard review. I've submitted a pull request that addresses this, but doesn't have the compactness via rearranging things. Just takes out some fluff for the meantime.

**Comment by tehstone** [comment]
Compact Card is effectively on hold until someone volunteers to pick up work on it so this fix will not be made at this time.
